### ISSUE TITLE
clone 1.0.3

### ISSUE THREAD

**Issue by rimkov** [StudiUM/moodle-qtype_tcs#1]
Bonjour,

Je n'utilise pas le store moodle pour installer les plugins mais le dépôt Github et je m'aperçois que la version 1.0.3 n'est pas taguée, comment faire ? idem pour les plugins concordance en 1.0.4 et qtype_tcsjudgment et 1.0.3

Merci pour votre aide.

**Comment by leblangi** [comment]
Bonjour,

Nous avons créés les tags manquants pour les plugins qtype_tcs, qtype_tcsjudgment et concordance. Je vous inviterais cependant à prendre les dernières versions qui sont maintenues et à jour.
